### ISSUE TITLE
Action Points 12.07.23

### ISSUE THREAD

**Issue by AAG-DC** [HariharRengan/maths-game#1]
- [x] Add more common climbs; digits of pi, cube numbers
- [x] Start completion of the fractions tab. First look at multiplication; the issue here is that the chosen fraction should look to simplify a little bit. E.g.  3/17 * 4/13 is a bad choice...
- [x] Next is division. Similar to above.
- [x] Next look at addition and subtraction. There are good common denominators to use. Most common should be (2, 3, 4, 5, 6, 8, 10, 12). Less common should be (15, 20, 25). CHOICE: Should the user be allowed to write unsimplified fractions as their final answer?
- [x] Once the fractions are done, look at user-friendliness for this tab. Should there be two boxes, each for the numerator and denominator? Or should the user type with a slash '/' ?
- [x] Can the website store the number of 'incorrect answers' given as a hidden counter? This way, at the end we can give summary statistics such as "Avg. time per question, Avg. accuracy (this will need the counter for # of incorrect entries) etc.".
- [x] Currently there is a default on the main tab which is good. Can we add a header at the top of the page where we have more pre-filled defaults (e.g. 'Year 7' will be suitable for Year 7s, and will look at multiplication up to 12, whereas 'Year 11' might look up to 20)
- [x] Add a small footer. At the bottom right it should read 'Website coded by Harihar Rengan'

**Comment by HariharRengan** [comment]
The user has not been allowed unsimplified fractions.
I think that two boxes is better, as the slash notation is discouraged in school.
I have left the footer out for now

**Comment by HariharRengan** [comment]
Finished final task, styling originally clashed too much
