### ISSUE TITLE
Action Points 21.07.23

### ISSUE THREAD

**Issue by AAG-DC** [HariharRengan/maths-game#2]
- [x] On the main page, as well as storing the correct/incorrect responses, can we store 'number of skips' as a piece of data to give at the end? 
- [x] When completing a climb, a message pops up "Great job! You got ___ on the ___ climb." Can this be customised depending on how well the climb went? E.g. the message says "Great job!" when scoring 0, which seems taunting... Perhaps if they get 0, it gives a more detailed description of the climb. For 1-10, it says something motivational (keep going/you can do better etc.), and for 10+ it says "great job". Similar for the main page when presenting at the end.
- [x] When doing the climb, there is a small delay (I believe due to loading a fresh page, since the link at the top changes). Is there a way to make it 'embedded' in a single page to reduce lag/loading time? This also means that during the climb, I can manipulate the site. E.g. if I type localhost:5000/climbs/pi/90, then I score 89 without typing any digits. Unlikely that anyone would do this, but it may be abused in a way if a teacher says to reach a certain target and a student wants to skip this
- [x] Currently on the fractions page, it displays the fractions with a diagonal slash. Can this be horizontal? Also rather than naming the operation, can the display show the operation as a calculation? This might make it easier to think about.
- [x] On the fractions page, add an option to include the more difficult (i.e. less common) denominators or not.
- [x] On the fractions page, sometimes a whole number is generated e.g. 8/1. Can this be displayed as 8, rather than 8/1?
- [x] **NEW TAB** Can we make a new tab for mixed fractions? Similar to the fractions tab in its generation, but this should have a whole number and proper fraction part. Similarly, the required answer should be a whole number with a proper fraction. Also would be suitable if it could be displayed as a calculation (see the 4th checkpoint in this list). _Be wary of generating proper fractions with a denominator of 1. This should not be allowed._

**Comment by AAG-DC** [comment]
P.S. Superb work so far Harihar! Please note that I will not be able to check that often during the holidays, so do not worry if you do not hear from me over the course of a week.

**Comment by HariharRengan** [comment]
- I could not add the information system for those who got 0 as the app cannot tell exactly what climb it is, but I have a customized message instead (2)
- The problem has been fixed for all except the pi and Fibonacci climb. Those two use the old interface, but the others and the custom climbs use the new one (3)
- I have not added the displayed calculations for now as they clash with the styling, although I have added the horizontal fraction bar (4)

**Comment by HariharRengan** [comment]
Dear Mr. Aggarwal,
Sorry to disturb, but I have completed the Action Points for now. I have
left the full summary on GitHub. Thank You!
Kind Regards,
Harihar Rengan
