### ISSUE TITLE
Percentages tab

### ISSUE THREAD

**Issue by AAG-DC** [HariharRengan/maths-game#4]
- In the percentages of amounts, sometimes it asks for 0% or 100%. These should be excluded
- Also in percentages of amounts, can we consider any multiple of 5 (e.g. 5% or 35%), but with half the weighting of the other common ones? E.g. 25% should be twice as likely to come up as 5%, but 5% still has a chance of being a question.
- Change name of second version to 'Percentage Change problems', and allow for percentage decreases as well as increases.
- In the percentage changes, same as above: 0% and 100% should be excluded, multiples of 5% should be included.

**Comment by HariharRengan** [comment]
Completed
