### ISSUE TITLE
Fixes & New Content

### ISSUE THREAD

**Issue by AAG-DC** [HariharRengan/maths-game#5]
- When generating fractions, add logic in the generator to ensure the numerator and denominator are not multiples of each other; sometimes integers are generated, giving e.g. "1 + 3" in the fractions tab.
- When generating fractions, add logic in the generator to ensure for addition that the fractions have different denominators, else the purpose of the task is lost.

-*NEW TAB* Find the HCF and LCM of two numbers. It would be good to have a 'pool' of numbers (since primes are awful). Also, the two numbers used should not be multiples e.g. 12 and 24 are a bad pair.

-*NEW TAB* Index Laws - find the index when simplified. This should have an easy and difficult tab.

1. Easy: Positive and negative integers only for the indices.
2. Difficult: Positive, negative and fractional indices.
The tab should make use of the main power laws (addition when multiplying, subtraction when dividing, multiplying when raised to a further power).
It would work best if there were coefficients involved as well.
E.g. "Simplify 4x^7 * 3x^-2", and the user would input '12' for the coefficient and '5' for the power.
Also, it would be good if there were a 2-4% chance that the question "What is 4x^0?"/"What is 7x^0?" came up, to test this index identity. This may require a different answer box design, since other questions require two inputs from the user and this will require only one input.

*NEW TAB* BIDMAS (Order of Operations). This will be a difficult one and will require some careful thought to generate questions. We are looking for questions where BIDMAS is important. It may be useful to look at worksheets on the internet for inspiration and try to think how they made their questions.
Since this tab is difficult, let's work on it in the long term.

**Comment by HariharRengan** [comment]
Added the above features
