### ISSUE TITLE
Final (?) overhaul

### ISSUE THREAD

**Issue by AAG-DC** [HariharRengan/maths-game#6]
Arithmetic:
- Change name from Math Game to 'Quick Arithmetic'

Climbs:
- Show button for 'Try Again', and below this show boxes for the other climbs on the main climbs page.
- Add image/icon for each climb
Pi Climb - symbol of Pi
Prime Climb - the first few primes...
Fibonacci Sequence - symbol of the Fibonacci spiral
Square Numbers - use the image of 5^2 from https://nzmaths.co.nz/sites/default/files/images/NL4P14C.GIF
Triangular Numbers - use the image of T_5 from https://cdn1.byjus.com/wp-content/uploads/2016/06/triangular-numbers.jpg
Cube Numbers - use https://i.shgcdn.com/dcf14086-33ae-4303-aecc-6b2b74786da2/-/format/auto/-/preview/3000x3000/-/quality/lighter/

- Is it possible to add a cookie that tracks your record for each climb, and can display it (e.g. next to the 'start climb' button, it says "Record: __")

*Pi Climb
	- "You got up to X decimal places on the π climb"
	- Only allow one digit entry into the box, in case some people are typing too fast...

*Prime Climb
	- "You got the first X primes in the prime climb"

*Fibonacci Climb
	- Not working...

*Square Number Climb
	-This page accepts the inputs noticeably faster. Is there a reason why? (Not pulling from a list?...)

Fractions (and Mixed Fractions):
- Make 'Check Answer' button responsive to the 'Enter' key, instead of requiring a click.
- Change 'Difficult' button to say 'Change to Difficult', to make it clear that the user is currently doing the easy questions.
- Same as above, for the 'Easy' button
- Often when multiplication and division come up, the same denominators are chosen. For multiplication/division, can a logic be applied to generator to ensure different denominators are chosen MOST of the time?

Mixed Fractions:
- One sum was "14/25 - 16/25".
	Entering the following came up as incorrect:
	-Integer part : 0
	-Numerator: -2
	-Denominator: 25
	Entering the following came up as correct:
	-Integer part : 0
	-Numerator: 2
	-Denominator: 25
- Another sum was "9/10  ÷ 3/10"
	Entering the following came up as incorrect:
	-Integer part : 3
	-Numerator: 0
	-Denominator: 0
	Entering the following also came up as incorrect:
	-Integer part : 3
	-Numerator: 0
	-Denominator: 10
	I could not figure out what the correct answer would be...

Binomial:
- Change description: "Enter the binomial coefficients for (1+x)^X. Enter the coefficients in order of ascending powers of x, with a comma between the coefficients."

* Add an option similar to fractions for "Change to Difficult".
	- The difficult tab will ask for the coefficients of (a + bx)^X. The possible values of a and b should be limited to between -4 and 4. This will also put in good practice for negative signs. 
	- The powers should only go as high as 6 now, since the coefficients will be much larger.
	- The values of a and b should also be different (otherwise they could just be factored out, which would not happen in an exam question)
	- If a or b are generated as 4 or -4, then the power of X should not be 6, to make the coefficients manageable

Percentages:
- Change toggle button to say "Percentages of Amounts" instead of "Percentage of Numbers"
- Make 'Check Answer' button responsive to the 'Enter' key, instead of requiring a click.
- One sum was "40% of 198". The answer 79.2 was "incorrect."
	- Happened again with "35% of 36". Possibly an issue calculating when the answer is a decimal?
- "Increase 0 by 10%". 0 should be removed from the pool of generated numbers, for both Percentages of Amounts and Percentage Change Problems.

HCF & LCM:
- Make 'Check Answer' button responsive to the 'Enter' key, instead of requiring a click.

Index Laws:
- Make 'Check Answer' button responsive to the 'Enter' key, instead of requiring a click.
- Change 'Difficult' button to say 'Change to Difficult', to make it clear that the user is currently doing the easy questions.
- Include the power law for both easy and difficult: (x^n)^m = x^(n*m)
- Include questions where x has a coefficient, and add an input both for the coefficient
- In the difficult indices, change the display of the fractional indices to display as a fraction. Currently reads with a division sign.
- Error encountered after generating a few questions (see below)
127.0.0.1 - - [17/Oct/2023 09:42:25] "GET /index-laws/1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\Anuj.Aggarwal\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Anuj.Aggarwal\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Anuj.Aggarwal\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Anuj.Aggarwal\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Anuj.Aggarwal\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Anuj.Aggarwal\AppData\Roaming\Python\Python39\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Anuj.Aggarwal\Downloads\maths-game-main\app.py", line 484, in indlaws
    ans = round(((a * b) + 1) / a if op != '÷' else (1 - (a * b)) / a, 3)
ZeroDivisionError: division by zero
127.0.0.1 - - [17/Oct/2023 09:42:25] "GET /index-laws/1?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [17/Oct/2023 09:42:26] "GET /index-laws/1?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [17/Oct/2023 09:42:26] "GET /index-laws/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [17/Oct/2023 09:42:26] "GET /index-laws/1?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -

BIDMAS:
- Make 'Check Answer' button responsive to the 'Enter' key, instead of requiring a click.

**Comment by HariharRengan** [comment]
Completed
